name: Test xk6-webtransport

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Run prettier
        uses: creyD/prettier_action@v4.6
        with:
          dry: True

      - name: Lint code issues
        uses: golangci/golangci-lint-action@v8.0.0

      - name: Build k6 with xk6-webtransport
        run: |
          go install go.k6.io/xk6/cmd/xk6@latest
          xk6 build --with github.com/kelseyaubrecht/xk6-webtransport@latest
